### ISSUE TITLE
README_en.md

### ISSUE THREAD

**Issue by iykequame** [SeriniTY320/SELinux_Policy_Grabber#1]
# SELinux_Policy_Grabber

This simple script is designed to solve problems with SELinux for device trees. 
Using: Place the script in the root directory of the user Place next to the script log.txt (log file) format: https://gist.github.com/SeriniTY320/664aaa3d78aa86c4d3eb693121d93335#file-oreo_mt6735_sepolicy_error 

Execute     
```bash SELinux_grabber.sh``` In the ```~ / out / sepolicy``` directory there are files with the necessary rights based on errors in the log.

**Comment by SeriniTY320** [comment]
Do you want the eng translations in README?

**Comment by Dozerators** [comment]
Ебать братишка ты долбоеб земля тебе пухом

**Comment by iykequame** [comment]
@SeriniTY320 yes, it will help most of us who don't know/understand Russian language.

**Comment by SeriniTY320** [comment]
@iykequame okay. will add new functional and eng translation

**Comment by iykequame** [comment]
thats will great .
thanks
